[[override]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-google"
  source = "github.com/pulumi/terraform-provider-google"
  branch = "pulumi-master"
